Added dart implementation
std-uritemplate/std-uritemplate pull request #124
Opened 2024-02-05 17:25 UTC by ricardoboss

Fixes #123

2024-02-05 17:29 UTC, andreaTP commented on dart/std_uri_template.dart
> +      if (!const bool.fromEnvironment('dart.library.js')) {
Is this the best we can do in Dart?

2024-02-05 17:30 UTC, ricardoboss commented
In its current form, the dart file is not publishable as its own Dart package. That would require a `pubspec.yaml` with some metadata. Also, since [`pub.dev`](https://pub.dev) doesn't support namespaced packages, I didn't publish it as to leave the `std_uri_template` package name free for you to use.

2024-02-05 17:35 UTC, ricardoboss commented
Maybe the `StdUriTemplate` class should be made `abstract` or have a private constructor to prevent instantiating it.

2024-02-05 18:50 UTC, ricardoboss commented
> @andreaTP Do you mind sharing a good link on how to publish dart packages so that I can go through the required steps?

Dart is pretty well documented and you can find all you need here: https://dart.dev/tools/pub/publishing

2024-02-05 18:57 UTC, ricardoboss commented on dart/std_uri_template.dart
> +      if (!const bool.fromEnvironment('dart.library.js')) {
The link is for PHP, that should be removed; my bad. I'll look into it, but it should work in dart.js environments.

2024-02-05 19:04 UTC, ricardoboss commented
> @andreaTP I notice that you are re-allocating the StringBuffers while in (most of) the fully typed implementation we are "resetting" those for performance reasons.

The current implementation uses `token != null` to determine the current state. I could replace that with `token.isEmpty` and the allocations with `token.reset()`.

2024-02-05 19:22 UTC, ricardoboss commented on dart/std_uri_template.dart
> +      if (!const bool.fromEnvironment('dart.library.js')) {
Dart has typed `Map`s as opposed to PHP. The simpler check should suffice since we don't have to explicitly check if the `Map` could be a `List` (i.e. only integer keys).

2024-02-05 19:25 UTC, ricardoboss commented
I looked at the C# implementation and noticed they use more enums. I decided to stick with strings here, but enums may be better for performance. What is your preference?

2024-02-06 09:41 UTC, andreaTP commented
> I looked at the C# implementation and noticed they use more enums. I decided to stick with strings here, but enums may be better for performance. What is your preference?

My personal preference is for enums, but it's not a requirement.
You probably started the implementation from a dynamically typed language while the Java implementation is commonly used as the reference.

2024-02-06 10:20 UTC, andreaTP commented on dart/std_uri_template.dart
> +      if (!const bool.fromEnvironment('dart.library.js')) {
👍

2024-02-06 10:27 UTC, andreaTP commented
@ricardoboss I have reviewed your implementation and it looks like a solid starting point, thanks a lot!
Here is the list of what is left, in priority order:

- fix the failure in CI (I can reproduce locally) the error is not "File not found" but is failing on non-utf-8 characters:

```
Invalid argument(s): Illegal character identified in the token at col: 30
#0      StdUriTemplate._validateLiteral (file:///Users/aperuffo/workspace/std-uritemplate/dart/std_uri_template.dart:28:9)
#1      StdUriTemplate._expandImpl (file:///Users/aperuffo/workspace/std-uritemplate/dart/std_uri_template.dart:152:17)
#2      StdUriTemplate.expand (file:///Users/aperuffo/workspace/std-uritemplate/dart/std_uri_template.dart:7:12)
#3      main (file:///Users/aperuffo/workspace/std-uritemplate/dart/test.dart:29:35)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

- do we need a "Verified publisher" I cannot register a GH Pages as verified: `std-uritemplate.github.io` as I don't control the DNS. Do you know if there is a way?
- can you update the readme and the documentation?
- can you draft the release GH Action?

2024-02-06 21:34 UTC, ricardoboss commented
> fix the failure in CI (I can reproduce locally) the error is not "File not found" but is failing on non-utf-8 characters

Looking into it. I had similar issues running the tests locally, but shrugged it off hoping it was just a git issue on my machine.

> do we need a "Verified publisher" I cannot register a GH Pages as verified: std-uritemplate.github.io as I don't control the DNS. Do you know if there is a way?

AFAIK, that's the only way to create a verified publisher. It is possible to publish packages without being verified, but I wouldn't recommend that. Maybe the GitHub support can help? The pub.dev team could maybe also verify you?

> - can you update the readme and the documentation?
> - can you draft the release GH Action?

On it.

2024-02-06 21:52 UTC, ricardoboss commented
Automated releases to pub.dev are possible after the first version has been manually published. I prepared the workflow, but I **strongly advise you** to read through this document: https://dart.dev/tools/pub/automated-publishing#configuring-automated-publishing-from-github-actions-on-pubdev

It not only describes the idea behind automated publishing, it also guides you how to set it up and harden its security.

2024-02-06 23:02 UTC, ricardoboss commented
A curiosity about the the 'Language native date-time format' test: Dart implemented the ISO 8601 including the milliseconds, so instead of `2023-02-13T18:49:00Z` it results in `2023-02-13T18:49:00.000Z` (which is also ISO 8601). I added the formats including the milliseconds to the `edge-cases.json` as alternative results.

2024-02-07 01:02 UTC, ricardoboss commented
@andreaTP all tests pass locally. I not sure whether I should redo the `StringBuffer` allocations. LMK if I should adjust anything, also happy to answer any questions or provide support regarding publishing!

2024-02-07 11:16 UTC, andreaTP requested changes
Thanks for bearing with me in this process @ricardoboss !
This looks almost good to merge, things left for you:

- please emit the date in the proposed format
- change the package name to `std_uritemplate` ( 🙏 )

For me:

- need to register the Verified Publisher, tentatively opened [this PR](https://github.com/proj-at/subdomains/pull/23) to have a valid domain for free

2024-02-07 11:16 UTC, andreaTP commented on dart/lib/std_uri_template.dart
> +    result.write('');
is this needed?

2024-02-07 11:16 UTC, andreaTP commented on uritemplate-test-additional/edge-cases.json
> +        ["{+nativedate}", ["2023-02-13T18:49:00Z", "2023-02-13T18:49:00.000Z"]],
I know that this is another possible and valid output, although, to keep this implementation results predictable across implementation I have to ask you if it's possible to generate the proposed format (i.e. removing `.000`) using a DateTime Formatter or something similar.

2024-02-07 11:17 UTC, ricardoboss commented on uritemplate-test-additional/edge-cases.json
> +        ["{+nativedate}", ["2023-02-13T18:49:00Z", "2023-02-13T18:49:00.000Z"]],
Sure that's possible! I'll revert this change and adjust the format.

2024-02-07 11:18 UTC, ricardoboss commented on dart/lib/std_uri_template.dart
> +    result.write('');
Oops, oversight on my part. Should not be needed.

2024-02-07 11:23 UTC, ricardoboss commented on uritemplate-test-additional/edge-cases.json
> +        ["{+nativedate}", ["2023-02-13T18:49:00Z", "2023-02-13T18:49:00.000Z"]],
One thing though: Using `DateFormat` requires a dependency on the `intl` package. I think we both want to avoid dependencies. Should I add it anyway or resort to string manipulation to remove the milliseconds after converting the date to string?

2024-02-07 11:28 UTC, andreaTP commented on uritemplate-test-additional/edge-cases.json
> +        ["{+nativedate}", ["2023-02-13T18:49:00Z", "2023-02-13T18:49:00.000Z"]],
There should be no external dependencies, you are right, from what I see the best would be to have a self-contained function that does something similar to the standard library:

```dart
  String m = _twoDigits(month);
  String d = _twoDigits(day);
  String h = _twoDigits(hour);
  String min = _twoDigits(minute);
  String sec = _twoDigits(second);
  return "$y-$m-${d}T$h:$min:$secZ";
```

2024-02-07 11:36 UTC, ricardoboss commented on uritemplate-test-additional/edge-cases.json
> +        ["{+nativedate}", ["2023-02-13T18:49:00Z", "2023-02-13T18:49:00.000Z"]],
Done

2024-02-07 12:13 UTC, andreaTP commented on dart/CHANGELOG.md
> +# 0.0.1
According to [this](https://dart.dev/tools/pub/publishing#important-files) the Changelog is not strictly needed ...
This is not going to be maintained ...

2024-02-07 12:22 UTC, andreaTP commented on dart/pubspec.yaml
> +version: 0.0.1
We should update this version dynamically like we do, e.g. for typescript.

Something like this:

```
cat <<< $(yq e -M ".version = \"${GITHUB_REF_NAME}\"" pubspec.yaml) > pubspec.yaml
```
in the release workflow should make it ...

2024-02-07 12:22 UTC, andreaTP commented on .github/workflows/release.yml
> +      - name: Install dependencies
Should we run this command in the `dart` folder?

```
working-directory: dart
```

2024-02-07 12:38 UTC, andreaTP reviewed
A couple of minor asks again, but it looks good to me overall, thanks for the contribution!

Let me wait to see if I can register the subdomain, I'll try a first release from my machine, I'll merge the PR and we finalize a proper automated release.

2024-02-07 15:05 UTC, andreaTP commented on dart/lib/std_uritemplate.dart
> +  String toIso8601StringWithoutMilliseconds() {
Implementation wise looks good, thanks for the change!
Please help me with Dart semantics, is this going to be public?
E.g. can a user use this function after importing the library?

Do we have a way to make it visible only to the current file/compilation unit?

2024-02-07 15:15 UTC, ricardoboss commented on dart/lib/std_uritemplate.dart
> +  String toIso8601StringWithoutMilliseconds() {
No. In Dart, `extension`s are only accessible from outside the file if they have a name (i.e. `extension DateTimeExtension on DateTime {...}`). I am testing the library in another project and the extension method is not accessible.

2024-02-07 15:19 UTC, ricardoboss commented on .github/workflows/release.yml
> +      - name: Install dependencies
Yes, good catch!

2024-02-07 15:25 UTC, ricardoboss commented on dart/pubspec.yaml
> +version: 0.0.1
I used `sed` instead. Hope that's fine.

2024-02-07 15:25 UTC, ricardoboss commented on dart/CHANGELOG.md
> +# 0.0.1
Removed

2024-02-07 15:26 UTC, andreaTP commented on dart/lib/std_uritemplate.dart
> +  String toIso8601StringWithoutMilliseconds() {
perfect, thanks for the clarification 👍

2024-02-08 09:41 UTC, ricardoboss commented
@andreaTP I think I addressed all comments. Can you review again?

2024-02-08 10:22 UTC, andreaTP requested changes
A couple of very last comments, I think this is good and basically ready to merge(in case I can fix things on top).
I'm waiting to merge only to see if I can get the sub-domain verified for free.

An alternative approach would be to comment out the "release" section, merge this PR and continue in a follow-up PR.
As you prefer 🙂 thanks a lot for this great contribution!

2024-02-08 10:22 UTC, andreaTP commented on dart/test.dart
> +    print("false");
Sorry if I missed this earlier, but this is incorrect, in case there are errors loading the file it's a "tool" issue and we should just explode.

2024-02-08 10:22 UTC, andreaTP commented on dart/pubspec.yaml
> +version: 0.0.1
Just not ideal, have you experienced issues with my proposal?

2024-02-08 10:22 UTC, andreaTP commented on dart/test.dart
> +    print("false");
missed this as well, in this case, we should throw the exception and exit without printing a valid output.

2024-02-08 10:27 UTC, ricardoboss commented on dart/pubspec.yaml
> +version: 0.0.1
Yeah, the command you provided replaced the whole file content with just `version: ...`.  Maybe it is because I am using bash on Mac. I thought `sed` might be the better tool to achieve the task. But happy to adjust as you wish!

2024-02-08 10:29 UTC, ricardoboss commented on dart/test.dart
> +    print("false");
Now throwing

2024-02-08 10:29 UTC, ricardoboss commented on dart/test.dart
> +    print("false");
Fixed

2024-02-08 10:30 UTC, ricardoboss commented
> An alternative approach would be to comment out the "release" section, merge this PR and continue in a follow-up PR.

I think I'd like that solution.

One other thing: should I add myself to the `CODEOWNERS` file for `*.dart`?

2024-02-08 11:13 UTC, andreaTP commented on dart/pubspec.yaml
> +version: 0.0.1
Just tested on Mac with `yq` version `4.24.2` and it works as expected ... but ... well, is a nitpick, feel free to ignore me.

2024-02-08 11:16 UTC, andreaTP commented
> I think I'd like that solution.

Ok, let's proceed in this way 👍 

> One other thing: should I add myself to the `CODEOWNERS` file for `dart/`?

Thanks for the proposal! Yes, please, be my guest 🙏 , much appreciated!

2024-02-08 11:28 UTC, andreaTP approved these changes
Last nitpick and I invited you as a collaborator on this repo.
LGTM, great work!

2024-02-08 11:28 UTC, andreaTP commented on Readme.md
> +| Dart | ✅ | ❌ | ✅ |
I promise this is the last one, can you get an X on the "Releaded" column

2024-02-08 11:31 UTC, ricardoboss commented on Readme.md
> +| Dart | ✅ | ❌ | ✅ |
Sorry, but I don't see this column 🙃  Did you mean "Reviewed"? That one already has an X, though. (I am not 100% sure what that means)

2024-02-08 11:31 UTC, ricardoboss commented on Readme.md
> +| Dart | ✅ | ❌ | ✅ |
Ohhhh published, yeah that makes more sense

2024-02-08 11:39 UTC, andreaTP commented on Readme.md
> +| Dart | ✅ | ❌ | ✅ |
yes, published 😅 

> I am not 100% sure what that means

We normally use it when, at least one expert in the specific language other than the author has reviewed the code.

2024-02-08 11:40 UTC, merged

2024-02-08 11:40 UTC, andreaTP commented
A pleasure working with you @ricardoboss 🙏