chore: add browser tests for typescript
std-uritemplate/std-uritemplate pull request #131
Opened 2024-02-19 18:20 UTC by musale

- Adds browser tests for typescript

TODO:
- [ ] update CI setup for typescript to allow headless browser testing
- [ ] update contribution doc/typescript readme to show how to trigger browser tests

2024-02-20 12:24 UTC, andreaTP requested changes
Thanks a lot for starting this effort!
I'm afraid this PR is not going in the expected direction.

What I'd expect:
- a separate folder `typescript-browser`
- a `test.sh` able to run the current Black Box tests without explicit references to sections etc.
- as little as possible(possibly no) usage of testing framework/infrastructure (favor using directly a headless browser)

Let me know if you have any further questions!

2024-02-20 15:33 UTC, musale commented
@andreaTP thank you for the feedback. Expectation 1 and 2 is straightforward. For 3, there's a challenge with:
1. passing the test data along. In the current setup, the data is passed as arguments for bash scripts. In `typescript` you get to use `process.argv` (node api) to get the test data and execute. In a browser setup, there's no way I'm aware to pass this data to a script that is being executed apart from importing the file directly from the folders it's in. The idea I have is to create a test script that has all the test data in it, load it into a DOM of a headless browser and execute it. This breaks the current testing setup:
  a. all test data is loaded when the test is triggered.	
  b. all tests will run when this part of the tests is triggered. There's no _per file_ testing.

    Is there an expectation to keep the testing setup as it is or does this scenario allow for a different testing pattern?

 2. headless browsers have complex api, hence helpful libraries like puppeteer are used to give the high level apis. I plan to try and run a headless instance, load the scripts and execute. This I'll do directly, if unsuccessful, then with [puppeteer](https://developer.chrome.com/docs/puppeteer). If this proves challenging, is there room to keep using https://vitest.dev? IMO if we allow a testing framework/infrastructure, it's a simple, little config option.

2024-02-20 17:16 UTC, andreaTP commented
> The idea I have is to create a test script that has all the test data in it, load it into a DOM of a headless browser and execute it.

This looks like a pretty viable approach!
Writing a custom `test.js` you should be able to load the content of `template.txt` and `substitutions.json` on a per-run basis instead of the entire test files.

> then with [puppeteer](https://developer.chrome.com/docs/puppeteer)

I'm fine using tools like puppeteer to ease the implementation of the test infrastructure.
I hope this unblocks you, let me know if you need further discussion.

2024-03-06 23:41 UTC, andreaTP reviewed
Looks like a very promising update! Thanks! Let me know when it is ready for review:+1: Thanks for the effort.

2024-03-07 15:39 UTC, musale commented on typescript-browser/tsconfig.json
@andreaTP I created this file to compile the `typescript/src` code to "ESNext". Currently, `typescript` compiles to commonjs which has issues on the browser. JS landscape is moving away from commonjs to es modules. Is it something to consider especially now we test for browser?

2024-03-08 14:39 UTC, andreaTP commented on typescript-browser/tsconfig.json
Summoning @riccardo-forina to help with this.

2024-03-11 09:46 UTC, andreaTP reviewed
@musale sorry for the delay, a few minor comments but this is definitely going in the right direction, thanks a lot!

2024-03-11 09:46 UTC, andreaTP commented on typescript-browser/test.js
> +  (async ()=>{
would you mind running a code formatter on this file?

2024-03-11 09:46 UTC, andreaTP commented on typescript-browser/test.js
> +        content: `${pkgContent};window.StdUriTemplate = StdUriTemplate;`,
If I understand it correctly it should be possible to use `path` instead of inlining the content:
https://pptr.dev/api/puppeteer.frameaddscripttagoptions

2024-03-11 09:46 UTC, andreaTP commented on typescript-browser/test.js
> +      process.exit(0);
in case of errors we should not return 0

2024-03-11 09:46 UTC, andreaTP commented on typescript/tsconfig.json
> +}
any reason for this formatting?

2024-03-11 10:59 UTC, andreaTP commented on .github/workflows/test.yml
> +        if: matrix.language == 'typescript-browser'
You need to add `typescript-browser` to the matrix

2024-03-12 09:12 UTC, musale commented on typescript-browser/test.js
> +        content: `${pkgContent};window.StdUriTemplate = StdUriTemplate;`,
Yes, you can use path. However, that will load the package content only and we can't reference `StdUriTemplate` in the browser. We need to add the `StdUriTemplate` to the `window` object so that we can call it in `page.evaluate` within a browser context. Also, `path` and `content` can't exist together.

2024-03-12 10:26 UTC, andreaTP commented on typescript-browser/test.js
> +        content: `${pkgContent};window.StdUriTemplate = StdUriTemplate;`,
Thanks for explaining

2024-03-18 10:24 UTC, andreaTP commented
Fixed in #139 thanks a lot for spearheading the effort @musale !

2024-03-18 10:24 UTC, closed without merging