#162 Switch to license expression
std-uritemplate/std-uritemplate pull request #163
Opened 2024-04-17 09:11 UTC by thompson-tomo

Closes #162

2024-04-17 09:13 UTC, andreaTP commented on csharp/Std.UriTemplate.csproj
> -    <PackageLicenseFile>LICENSE</PackageLicenseFile>
Do we need to remove this line?

2024-04-17 09:13 UTC, andreaTP commented
Thanks for making the changes, other than keeping the reference to the file lgtm.

2024-04-17 09:33 UTC, thompson-tomo commented on csharp/Std.UriTemplate.csproj
> -    <PackageLicenseFile>LICENSE</PackageLicenseFile>
Na, it is fine to leave it in as it results in the license file also being included in the package.

2024-04-17 09:35 UTC, thompson-tomo commented
Keeping the reference will result in the license file also being included in the package.

2024-04-17 10:08 UTC, andreaTP commented
thanks for reverting back @thompson-tomo 

> Keeping the reference will result in the license file also being included in the package.

Is there anything wrong with it? I thought it was a best practice.
I'm not sure about .NET standards, I'll defer to @baywet and/or @andrueastman the final decision.

2024-04-17 11:36 UTC, baywet requested changes
From reading [the specification](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg), I couldn't find that one was necessarily better than the other.
A little history: license information used to be caried via a URL. This was bad for multiple reasons: people needed to click (time consuming, broken links, privacy, content change, etc...), and the nuget platform couldn't parse the information.
For that reason, [using a URL nowadays is discouraged](https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#types-of-recommendations)
The nuget team introduce the file and the expression fields in an effort to collocate the license with the package and alleviate the URL issues.
From reading between the lines, I believe the expression has slight advantages:
- smaller package to download.
- less parsing effort from nuget.org to "understand" the license.
The main tradeoff I can see being:
- the actual content of the license on GitHub and the template from nuget referred to by the expression could differ.

I hope that helps making a choice either way.

2024-04-17 11:36 UTC, baywet commented on csharp/Std.UriTemplate.csproj
> +    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
if the goal is to reduce the package size, the block line 53 should also be removed

2024-04-17 11:39 UTC, baywet commented
If we want to diff our license file against the template, here is the source https://spdx.org/licenses/

2024-04-17 11:42 UTC, thompson-tomo commented on csharp/Std.UriTemplate.csproj
> +    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
My goal is to facilitate license usage via SBOM'S however happy to remove the file if desired.

2024-04-17 11:43 UTC, baywet commented
I just ran a diff, they are identical except for formatting and the fact that Red Hat is in the copyright (should it?)

2024-04-17 11:44 UTC, andreaTP commented
> Red Hat is in the copyright (should it?)

I probably took it from another RH project, I'm fine removing the attribution.

2024-04-17 11:54 UTC, baywet commented
> > Red Hat is in the copyright (should it?)
> 
> I probably took it from another RH project, I'm fine removing the attribution.

Since we made a point of creating a separate organization, project, etc... it'd make sense to align licensing as well.
Since we don't have a legal entity behind this project, I think our only option would be to set individuals.
And I don't want to "take credit for work you've mostly done", but for a "hit by a bus reason" I think it'd make sense to have multiple individuals here.
What do you think?

2024-04-17 11:58 UTC, andreaTP commented
No strong opinions, I would be fine leaving it empty but feel free to proceed as you think is the best.

2024-04-17 12:31 UTC, andreaTP commented
This should be the answer: https://www.apache.org/licenses/LICENSE-2.0#apply
To me it can be:

> Copyright 2023 std-uritemplate

Optionally with a link to: https://github.com/orgs/std-uritemplate/people
But, again, I'm really not fussy about this.

2024-04-17 12:33 UTC, baywet commented
I think you just found the perfect solution!

2024-04-17 15:28 UTC, andreaTP commented
@baywet do you mind to recap the next steps?

additional note: I'm extracting the C# implementation to a separate repo: https://github.com/std-uritemplate/std-uritemplate-csharp so I'll probably ask to direct this PR there sometime soon.

2024-04-17 16:24 UTC, baywet commented
sure:
- [ ] remove the property group block that includes the license file from the csproj
- [ ] update the license file to set the copyright to `Copyright 2023 std-uritemplate`

CC @thompson-tomo

2024-04-17 21:50 UTC, thompson-tomo commented on csharp/Std.UriTemplate.csproj
> +    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
File removed

2024-04-17 21:51 UTC, thompson-tomo commented
@baywet ok, the changes requested are done.

2024-04-18 08:19 UTC, andrueastman approved these changes

2024-04-18 10:37 UTC, andreaTP commented
Superseeded by #165 and https://github.com/std-uritemplate/std-uritemplate-csharp/pull/2

2024-04-18 10:37 UTC, closed without merging