Add generated release configuration
std-uritemplate/std-uritemplate pull request #203
Opened 2024-07-04 11:08 UTC by ricardoboss

...and generate a CHANGELOG.md for certain packages.

This PR should fix #198 as this automates including the CHANGELOG in packages and makes it easier to manage releases via GitHub.

Future PRs will need to be tagged correctly and I have taken the liberty to add new tags (`ignore-for-release` and `breaking-change`) that can be used to categorize them in the releases.

You might also notice that I have created a new GitHub action just to generate the CHANGELOG.md from the GitHub releases, as I was unable to find such an action. It just fetches the releases from GitHub, takes their markdown bodies and writes them all into a file.

I only added the generation for Dart and C# since I already know how to include them in their respective packages.

2024-07-04 11:32 UTC, baywet commented on .github/workflows/release.yml
> +      - name: Generate Changelog
this is an interesting approach. Wouldn't the latest release always be missing with that?
Usually the commit history/a manually maintained changelog file is what drives the content in the releases, not the other way around.
I'd like to get @andreaTP opinion on this one.

2024-07-04 11:39 UTC, ricardoboss commented on .github/workflows/release.yml
> +      - name: Generate Changelog
Not if the release (and tag) are created solely via GitHub. GitHub will add the tag as soon as the release is created and that will trigger the workflow.

In my understanding this was the intended workflow for the future.

2024-07-04 11:40 UTC, ricardoboss commented on .github/workflows/release.yml
> +      - name: Generate Changelog
We can also change the trigger of the workflow to only run on release as opposed to when a new tag is pushed

2024-07-04 11:53 UTC, baywet commented on .github/workflows/release.yml
> +      - name: Generate Changelog
understood. I'd like Andrea's input since he is the one who configured all the CI/CD here.
My thoughts were to maybe configure release please on the repository to do the version bump and tag/release creation for us based off conventional commits.
We're started deploying it for Microsoft Graph and it has saved us a lot of time already. (but we release lots of packages weekly)

2024-07-22 15:49 UTC, andreaTP requested changes
Thanks again for the effort @ricardoboss , much appreciated!
A few questions, and, I would love to see a POC in action in a separate repo.

Additionally, since the changelog will integrate all the changes, does it make sense to generate it on the top level and copy it around when necessary?

2024-07-22 15:49 UTC, andreaTP commented on .github/release.yml
> +          - submodules
We should include submodules because of C# :cry: , luckily the other submodule is the uritemplate tests, which changes very rarely.

2024-07-22 15:49 UTC, andreaTP commented on .github/release.yml
> +        - submodules
We should include the submodules here as well.

2024-07-22 15:49 UTC, andreaTP commented on .github/workflows/release.yml
> +      - name: Generate Changelog
If I understand this correctly, it should work out of the box as the release tag is the triggering action for the release.

Ideally, we should test the behavior in another test repository to verify that all the dots are connected.

2024-07-22 15:49 UTC, andreaTP commented on .github/workflows/release.yml
> +        uses: ricardoboss/changelog-from-github-releases@v1
Not that I do not trust you @ricardoboss :smile: , but I'm curious why you have had to roll out your own action instead of using (and maybe configuring) a more widely used one.

2024-07-22 16:18 UTC, ricardoboss commented on .github/workflows/release.yml
> +        uses: ricardoboss/changelog-from-github-releases@v1
There are two reasons:
1. I didn't find one at first. There are tons of actions that do the opposite. Eventually, I found one alternative action that obviously has more users and does exactly the same: https://github.com/rhysd/changelog-from-release
  If you want me to, I will change the workflow to use theirs.
2. I always needed a reason to create my own action because I wanted to play around with it. I took this opportunity :D

2024-07-22 16:18 UTC, ricardoboss commented on .github/workflows/release.yml
> +        uses: ricardoboss/changelog-from-github-releases@v1
Oh and my action is open source for every one to look through: https://github.com/ricardoboss/changelog-from-github-releases

2024-07-22 16:20 UTC, ricardoboss commented on .github/workflows/release.yml
> +      - name: Generate Changelog
I will set something up...

2024-07-22 16:22 UTC, ricardoboss commented on .github/release.yml
> +          - submodules
I'm not sure I understand... This line excludes the PRs with the label "submodules" from being grouped under "Other Changes". Instead they are included below under "Dependencies". Is this not correct?

2024-07-22 16:47 UTC, ricardoboss commented on .github/workflows/release.yml
> +      - name: Generate Changelog
@andreaTP I verified this is working as expected in this "fork" of the project: https://github.com/ricardoboss/std-uri-template-release-test/

1. I pushed this feature branch to a blank repository as the main branch
2. I created a sample PR with a label that should show up in the release notes generated by GH (https://github.com/ricardoboss/std-uri-template-release-test/pull/6)
3. I needed to fix the version of my action, so another PR followed (https://github.com/ricardoboss/std-uri-template-release-test/pull/7)
  - I need to publish a "forked" version of the Dart package so the pipeline can push updates too
  - The "forked" version is unlisted and not discoverable: https://pub.dev/packages/std_uritemplate_release_test
4. I created a new release on GitHub, set it to create a tag `1.0.0` when the release is created and clicked on "Generate Release Notes"
5. I clicked "Publish release"

The results can be seen here in form of the release: https://github.com/ricardoboss/std-uri-template-release-test/releases/tag/1.0.0
and here in the automated release of the dart package and its changelog: https://pub.dev/packages/std_uritemplate_release_test/changelog

2024-07-22 17:23 UTC, andreaTP commented on .github/workflows/release.yml
> +      - name: Generate Changelog
Looks awesome! Thanks a lot for showing this example @ricardoboss !

2024-07-22 17:24 UTC, andreaTP commented on .github/release.yml
> +          - submodules
Oh, this only refer to the label, I missed it, it's fine :-) , thanks for explaining.

2024-07-22 17:26 UTC, andreaTP commented on .github/workflows/release.yml
> +        uses: ricardoboss/changelog-from-github-releases@v1
Thanks for the context, if you don't mind I'll ask you to use the `rhsyd` action as it already has some stars and possibly users ... I hope this will require less maintenance for us and reduce the risk bus-factor wise in the longer term.

> I always needed a reason to create my own action because I wanted to play around with it. I took this opportunity :D

Nice! :slightly_smiling_face:

2024-07-22 18:00 UTC, ricardoboss commented on .github/workflows/release.yml
> +        uses: ricardoboss/changelog-from-github-releases@v1
Not sure what I'm doing wrong, but in my test repo it tries to create a commit with the changelog and push it to the repo, which doesn't work... I'll have to figure out how to disable that

2024-07-22 18:05 UTC, ricardoboss commented on .github/workflows/release.yml
> +        uses: ricardoboss/changelog-from-github-releases@v1
Done

2024-07-23 10:07 UTC, andreaTP approved these changes
A nit, but lgtm overall, I'll take over and extend to all the languages after this one is merged.
Thanks as always @ricardoboss !

@baywet wdyt?

2024-07-23 10:07 UTC, andreaTP commented on .github/workflows/release.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
- nitpick - if we are not committing back to the repo we should not need this token

2024-07-23 10:55 UTC, ricardoboss commented on .github/workflows/release.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
If I'm understanding the readme correctly, the token is used to get the releases from github, because unauthenticated requests could be rate limited. I haven't tried without the token.

2024-07-23 11:42 UTC, baywet commented on .github/workflows/release.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
yep, from implementing the kiota search command, the rate limiting is much lower when anonymous than when authenticated.
Then, this token is fairly privileged. Maybe we could add a second permission block at the job level with lower permissions?

2024-07-23 11:46 UTC, andreaTP commented on .github/workflows/release.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
Thanks for the answers!
`GITHUB_TOKEN` is the default, the token with privileges is `GH_TOKEN`, I think it's fine :slightly_smiling_face:

2024-07-23 11:57 UTC, baywet commented on .github/workflows/release.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
[The documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#example-usage-of-the-secrets-context) would contradict this statement. AFAIK GH_TOKEN is what the CLI expects, while GITHUB_TOKEN is the token you get from the workflow infrastructure (with or without a permission block)

2024-07-23 12:05 UTC, andreaTP commented on .github/workflows/release.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
Double-checked, [those](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) are the permissions and the current setup is `Default access
(restricted)`

2024-07-23 12:16 UTC, baywet commented on .github/workflows/release.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
right, but we have a permission block for the whole workflow. https://github.com/std-uritemplate/std-uritemplate/blob/b0efac4e97cf09f3d4fa66b1049dacaf7ef3dba1/.github/workflows/release.yml#L8

2024-07-23 12:37 UTC, andreaTP commented on .github/workflows/release.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
I don't think that `permissions:` can extend the token permissions in any way ...
Anyhow, we can have a separate discussion and iterate over this point in a separate PR when required.

2024-07-23 12:37 UTC, merged

2024-07-23 12:40 UTC, baywet commented on .github/workflows/release.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
[it does change the token permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#defining-access-for-the-github_token-permissions) but ok to treat it as separate

2024-07-23 13:38 UTC, andreaTP commented on .github/workflows/release.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
Oh, wow, ok TIL!