Normalize dates to UTC when possible
std-uritemplate/std-uritemplate pull request #240
Opened 2024-09-11 17:47 UTC by andreaTP

There are too many nuances in between languages and, in Swift, TS and Dart there is no concept of "TimeZone" associated with a Date.
Hence, we decide to normalize dates to UTC when the functionality is available in the host language.

2024-09-11 17:49 UTC, andreaTP commented on dart/test.dart
> +    data['nativedatethree'] = DateTime.fromMillisecondsSinceEpoch(nativeDateThree, isUtc:false);
@ricardoboss this is the only "toggle" I found in Dart, which doesn't give us enough information to produce the correct "offset string", any suggestion?

2024-09-11 18:37 UTC, andreaTP commented
Another alternative would be to accept only UTC dates, and leave the language specific bits to the user (e.g. in abstractions for Kiota).

2024-09-12 10:53 UTC, andreaTP commented
Found another road blocker in Swift to this approach: https://stackoverflow.com/a/78093726/7898052

I think we should clearly state that we do support only UTC date-time and make sure all the implementations are consistent.

2024-09-12 11:10 UTC, andreaTP commented
Ready for review, this probably push the fix for #239 to the relevant `abstraction` library @baywet .
Let me know if this is reasonable or you have a better alternative.

2024-09-12 13:43 UTC, baywet requested changes
I don't think locking the offset to "no offset" is the right way to go here.
2024-09-12T09:40:23-04:00 might not always mean the same thing as 2024-09-12T13:40:23Z. Especially when you start using two date time to calculate durations and DST gets in the mix.

2024-09-12 13:43 UTC, baywet commented on dart/lib/std_uritemplate.dart
> +    return '$y-$m-${d}T$h:$min:${sec}Z';
wouldn't this assume this is always UTC and there cannot be any offset ?

2024-09-12 13:43 UTC, baywet commented on php/src/StdUriTemplate.php
> +            $value->setTimezone(new \DateTimeZone("UTC"));
why are we "forcing" the offset to no offset here?

2024-09-12 13:43 UTC, baywet commented on python/stduritemplate/__init__.py
> +            value.replace(tzinfo=timezone(timedelta(0)))
same comment about forcing the offset?

2024-09-12 13:58 UTC, andreaTP commented on dart/lib/std_uritemplate.dart
> +    return '$y-$m-${d}T$h:$min:${sec}Z';
Correct, we are already normalizing the date here:
https://github.com/std-uritemplate/std-uritemplate/blob/f9355e33b8e8ed1bda9b9f85ff3b3b7d12279e0c/dart/lib/std_uritemplate.dart#L472

2024-09-12 14:00 UTC, andreaTP commented on php/src/StdUriTemplate.php
> +            $value->setTimezone(new \DateTimeZone("UTC"));
This is not "forcing", this is "adjusting" the date to "no offset", so that the output (with the trailing `Z`) is going to be correct.

2024-09-12 14:02 UTC, andreaTP commented
> I don't think locking the offset to "no offset" is the right way to go here.

Feel free to come up with an alternative proposal @baywet , you can see(from the commit history on this branch) that I have attempted a few different variations, and I think that this is about "the best" that can be done here ...

2024-09-12 14:34 UTC, baywet commented on php/src/StdUriTemplate.php
> +            $value->setTimezone(new \DateTimeZone("UTC"));
but how do you _know_ this is the correct timezone?

2024-09-12 15:23 UTC, andreaTP commented on php/src/StdUriTemplate.php
> +            $value->setTimezone(new \DateTimeZone("UTC"));
Because is the only one we support, basically if you pass into the substitutions a Date that is not localized in UTC the timestamp is preserved and you get, as output, the version of the stringified date with the trailing `Z` (which is correct after normalization).

2024-09-12 16:50 UTC, pjmagee commented on python/stduritemplate/__init__.py
> +            value.replace(tzinfo=timezone(timedelta(0)))
What if the RFC 3339 date WITH timezone being provided, is actually an important piece of information. Is that becoming lost. We don't know the full reason behind someone uses or passing a date-time in a specific way, including with a timezone, there may be nuance we are skipping from a useability point of view? What if the server expects a timezone?

2024-09-12 17:44 UTC, andreaTP commented on python/stduritemplate/__init__.py
> +            value.replace(tzinfo=timezone(timedelta(0)))
Thanks for the feedback @pjmagee !

In this repository we strive to keep the minimum functionality that can be safely shared across languages.
If you need/want to use a Date with a specific format you can always serialize it to `String` before adding to the substitutions.

So far, it has been pretty straightforward, but with the growing number of languages and different nuances this seems to be more challenging than originally expected.
@baywet should we re-consider the handling of Dates out of this library and move the logic to `kiota-abstractions` where there is much more "context" and it can be, more precisely, handled?

2024-09-16 09:25 UTC, andreaTP commented
We decided to drop the Date support and release a 2.0 version

2024-09-16 09:25 UTC, closed without merging