PHP - Add strong typing and PHPDocs for better dev experience.
std-uritemplate/std-uritemplate pull request #80
Opened 2023-10-16 11:41 UTC by Ndiritu

- Uses strong typing to make it easier to catch bugs in future.
- Adds PHPDocs which enhance dev experience esp for `expand()`
- Fixes minor Exception handling cases.
- Updates PHP to reviewed on README.

closes https://github.com/std-uritemplate/std-uritemplate/issues/54

2023-10-16 11:42 UTC, Ndiritu commented on php/src/StdUriTemplate.php
> -                } catch (NumberFormatException $e) {
`NumberFormatException` doesn't exist in PHP

2023-10-16 11:43 UTC, Ndiritu commented on php/src/StdUriTemplate.php
> -        } else if (is_bool($value) || is_int($value) || is_float($value) || is_double($value)) {
`is_bool` is already checked in previous condition

2023-10-16 12:30 UTC, andreaTP requested changes
@Ndiritu thanks a lot for those improvements!
I really love them as they improve the quality of this PHP implementation.

Added a few comments inline but the only important one is to restore the "check + exception throw" in the `getMaxChar` method, please 🙏  I'm convinced that the current approach is more aligned with other implementations and easier to debug.

2023-10-16 12:30 UTC, andreaTP commented on php/src/StdUriTemplate.php
> -                } catch (NumberFormatException $e) {
To keep the implementation close to the others, we should verify and eventually catch the exception here, we can use an additional check like `is_numeric` to do the right validation.

2023-10-16 12:30 UTC, andreaTP commented on php/src/StdUriTemplate.php
> +                        } catch (TypeError $ex) {
Here we are catching ways more than exceptions coming from `getMaxChar`, I suggest we revert this detail.

2023-10-16 12:30 UTC, andreaTP commented on php/src/StdUriTemplate.php
> +                            throw new InvalidArgumentException("Cannot parse max chars at col: $i");
as above, this check should not be propagated.

2023-10-16 12:30 UTC, andreaTP commented on php/src/StdUriTemplate.php
> -                case 'LIST':
Can you please leave `LIST` before `MAP`?
The check to determine if it's a List is much much cheaper in terms of performance.

2023-10-16 12:30 UTC, andreaTP commented on php/src/StdUriTemplate.php
> -        } else if (is_bool($value) || is_int($value) || is_float($value) || is_double($value)) {
correct 👍 thanks!

2023-10-16 12:33 UTC, Ndiritu commented on php/src/StdUriTemplate.php
> +                        } catch (TypeError $ex) {
Yeah, fair point.

2023-10-17 06:57 UTC, Ndiritu commented on php/src/StdUriTemplate.php
> -                } catch (NumberFormatException $e) {
Used `is_int` to validate the type as well.

2023-10-17 06:58 UTC, Ndiritu commented on php/src/StdUriTemplate.php
> -                case 'LIST':
Added.

2023-10-17 13:13 UTC, andreaTP approved these changes
lgtm, great work @Ndiritu , thanks a lot!

2023-10-17 13:13 UTC, merged