Handle array and maps of primitive types
std-uritemplate/std-uritemplate pull request #95
Opened 2023-11-16 17:50 UTC by andreaTP

@baywet this is the demo implementation for the changes agreed [here](https://github.com/std-uritemplate/std-uritemplate/pull/94#discussion_r1395714581).
I implemented those only in Java for convenience, I'll expand to all of the languages if I have an ok from you (let me fight with Go tomorrow with an expert 🙂 ).

More specifically, I would like you to look at the added test cases(and add more if you wish).

(I sneaked in a little performance tweak for Java removing some allocations but it should still read well enough).

2023-11-17 11:01 UTC, baywet approved these changes
Yes I like this implementation. Although I think in the case of Go, some of the boxing you're doing won't be possible.

2023-11-17 15:33 UTC, baywet requested changes

2023-11-17 15:33 UTC, baywet commented on csharp/Std.UriTemplate.cs
> +        return false;
```suggestion
        return value switch {
            string or bool or int or long or float or double or DateTime or DateTimeOffset => return true,
            _ => false
        };
```

2023-11-17 15:33 UTC, baywet commented on csharp/Std.UriTemplate.cs
> +        throw new ArgumentException($"Illegal class passed as substitution, found {value.GetType()}");
```suggestion
        return value switch {
            string str => str,
            bool or int => value.ToString(),
            long or float or double number => number.ToString(CultureInfo.InvariantCulture),
            DateTime dt => dt.ToUniversalTime().ToString("yyyy-MM-dd'T'HH:mm:ssZ"),
            DateTimeOffset dto => dto.ToUniversalTime().ToString("yyyy-MM-dd'T'HH:mm:ssZ"),
            _ => throw new ArgumentException($"Illegal class passed as substitution, found {value.GetType()}"),
        };
```

we might need to break the number case into multiple cases

2023-11-17 15:33 UTC, baywet commented on go/go.mod
> +require github.com/stretchr/testify v1.8.4
again testity should be indirect I believe

2023-11-17 15:33 UTC, baywet commented on java/src/main/java/io/github/stduritemplate/StdUriTemplate.java
> +        if (value instanceof String ||
```suggestion
        if (value instanceof String) {
            return (String)value;
```

2023-11-17 15:33 UTC, baywet commented on java/src/main/java/io/github/stduritemplate/StdUriTemplate.java
> +            value instanceof Boolean ||
```suggestion
            } else if (value instanceof Boolean ||
```

2023-11-17 16:43 UTC, andreaTP commented on .gitignore
> +.vscode
I do prefer to avoid committing this

2023-11-17 16:43 UTC, andreaTP commented on csharp/Std.UriTemplate.cs
> +        return false;
oh, nice!

2023-11-17 16:46 UTC, andreaTP commented on go/go.mod
> +require github.com/stretchr/testify v1.8.4
This is automatically generated, `testify` is not "indirect" as it's not a transitive dependency of another module, I'm not sure how to declare a `test` scope only dependency, but @lburgazzoli probably knows.

2023-11-17 16:47 UTC, andreaTP commented on go/go.mod
> +require github.com/stretchr/testify v1.8.4
fun fact: you asked why I was not committing `go.sum` and turns out that `go.sum` is not generated for 0 dependencies projects 🙂

2023-11-17 16:47 UTC, andreaTP commented on java/src/main/java/io/github/stduritemplate/StdUriTemplate.java
> +        if (value instanceof String ||
right, I'll change this

2023-11-17 16:48 UTC, andreaTP commented on java/src/main/java/io/github/stduritemplate/StdUriTemplate.java
> +            value instanceof Boolean ||
right, I'll change this too

2023-11-17 17:08 UTC, andreaTP commented on go/go.mod
> +require github.com/stretchr/testify v1.8.4
ok, I decided to remove the dependencies, they are going to be used only when testing and we have to monitor that we don't commit them at the end.
Let see how this goes, or I'm open to suggestions!

2023-11-17 17:38 UTC, andreaTP commented on csharp/Std.UriTemplate.cs
> +        throw new ArgumentException($"Illegal class passed as substitution, found {value.GetType()}");
manually merged

2023-11-17 17:47 UTC, andreaTP commented
this is finally done 🙂 @baywet do you wanna review it again?

Please note that the Go implementation gets hidden in the changes view but is the ugliest and biggest.

I noticed that there is a Warning in CI saying that `isTrimmable` is not getting applied, [here](https://github.com/std-uritemplate/std-uritemplate/actions/runs/6907291453) for example, would you mind having a look? But let's keep the fix separated from this PR.

2023-11-17 17:49 UTC, baywet commented on csharp/Std.UriTemplate.cs
> +        throw new ArgumentException($"Illegal class passed as substitution, found {value.GetType()}");
We need to use to string overload with the invariant culture for any number type so that it doesn't get localized in some contexts (e.g. q million being represented as 1.000.000 in the us or pi being represented by 3.14 or 3,14 in depending on the locale)

2023-11-17 17:52 UTC, andreaTP commented on csharp/Std.UriTemplate.cs
> +        throw new ArgumentException($"Illegal class passed as substitution, found {value.GetType()}");
uh, ok, let me fix

2023-11-17 17:56 UTC, andreaTP commented on csharp/Std.UriTemplate.cs
> +        throw new ArgumentException($"Illegal class passed as substitution, found {value.GetType()}");
should be fixed now, please have a look

2023-11-17 17:59 UTC, andreaTP commented on csharp/Std.UriTemplate.cs
> +        throw new ArgumentException($"Illegal class passed as substitution, found {value.GetType()}");
with this change, apparently, also the CI warning disappeared!

2023-11-17 18:18 UTC, andreaTP commented
for future reference:
in this PR there is included a performance tweak for Java, C# and Go removing the unnecessary allocations of `StringBuilder`s

2023-11-17 18:50 UTC, baywet approved these changes
I think we can do a little bit better for c#.
For PHP cc @ndiritu @silaskenneth
For Python cc @samwelkanda

2023-11-17 18:50 UTC, baywet commented on csharp/Std.UriTemplate.cs
> +        };
```suggestion
        return value is string or bool or int or long or float or double or DateTime or DateTimeOffset;
```

2023-11-17 19:01 UTC, andreaTP commented
> I think we can do a little bit better for c#.

In terms of? Perf or style?

Do you want to wait for more reviews or we can merge and release?

2023-11-20 10:48 UTC, merged

2023-11-20 10:51 UTC, andreaTP commented
> For PHP cc @Ndiritu @SilasKenneth
 For Python cc @samwelkanda
 
 I merged it as this is an improvement anyhow, please feel free to review at your convenience and we will fix on top.